services:
  backend:
    image: node:lts-alpine3.21
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase
      - MONGO_URL=mongodb://root:example@mongo:27017/app?authSource=admin

  db:
    image: postgres:15-alpine3.20
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
      - ./mongo/SampleCollections:/SampleCollections
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    working_dir: /SampleCollections
    ports:
      - "27017:27017"

volumes:
  db_data: {}
  mongo_data: {}
