services:
  backend:
    image: node:lts-alpine3.21
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
