GET http://localhost:3000/users
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NTA0MTU1NzIsImV4cCI6MTc1MDQxOTE3Miwic3ViIjoiMSJ9.gPcikHaXOMGAJJl1_0O_eEJseUcRTdBpAmATSbJ425Y
# headers
#HEADERNAME: HEADERVALUE
#HEADERNAME: HEADERVALUE
#HEADERNAME: HEADERVALUE

#body

###
GET http://localhost:3000/users/1
###
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
    "isActivated": true
}
###
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "t@t.com",
    "password": "Azerty1234!",
    "isActivated": false
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "t@t.com",
    "password": "$2b$10$QgAWXF6DZRlZl.s32FYcTewyQHMiEY9nRjcKQKJe0BQGiLOlJhMy."
}