# headers
#HEADERNAME: HEADERVALUE
#HEADERNAME: HEADERVALUE
#HEADERNAME: HEADERVALUE

#body

###
GET http://localhost:3000/users/1
###
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
    "isActivated": true
}
###
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "t@t.com",
    "password": "Azerty1234!",
    "isActivated": false
}

###
# @name login
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "t@t.com",
    "password": "$2b$10$QgAWXF6DZRlZl.s32FYcTewyQHMiEY9nRjcKQKJe0BQGiLOlJhMy."
}

###
GET http://localhost:3000/users
Authorization: Bearer {{ login.response.body.token }}

###
POST http://localhost:3000/articles
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
    "title": "New Article User ID 1",
    "content": "This is the content of the new article.",
    "publicationDate": "2024-10-01T00:00:00Z",
    "UserId": 1
}